---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(lme4)
```


```{r}
df1 <- tibble(
  mu = rep(c(0),100000)
) %>%  
  rowwise %>% 
  mutate(
    sample_m = mean(rnorm(10,mu))
  )

df1 %>% ggplot(
    aes(
      color=as.factor(mu),
      x=sample_m
    )
  ) + 
  geom_density(
    size=1
  ) +
  theme_bw() +
  ggtitle("Sampling distribution when mu=0, n=5")+
  theme(
    text = element_text(size=15)
  )

  ggsave(
    "sampling_dist_0.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)
```


```{r}

df2 <- tibble(
  mu = rep(c(0,1),100000)
) %>%  
  rowwise %>% 
  mutate(
    sample_m = mean(rnorm(5,mu))
  ) 

df2 %>% ggplot(
    aes(
      color=as.factor(mu),
      x=sample_m
    )
  ) + 
  geom_density(
    size=1
  ) +
  theme_bw() +
  ggtitle("Sampling distributions when mu= 0 or 1, n=5")+
  theme(
    text = element_text(size=15)
  ) +
  geom_vline(
    xintercept = 0.737,
    linetype = "dashed"
  )

  ggsave(
    filename="sampling_dist_1_a.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)


```
```{r}
df3 <- tibble(
  mu = rep(c(0,1),10000)
) %>%  
  rowwise %>% 
  mutate(
    tidy(t.test(rnorm(5,mu)))
  ) 
  
```

```{r}
df3 %>% ggplot(
    aes(
      color=as.factor(mu),
      x=p.value
    )
  ) + 
  geom_density(
    size=1
  ) +
  theme_bw() +
  ggtitle("t-test p value distribution when mu= 0 or 1, n=5")+
  theme(
    text = element_text(size=15)
  ) +
  geom_vline(
    xintercept = 0.05,
    linetype = "dashed"
  )

  ggsave(
    filename="pvalue_dist_0.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)
```
```{r}
df4 <- tibble(
  mu = rep(c(0,1),100000)
) %>%  
  rowwise %>% 
  mutate(
    sample_m = mean(rnorm(20,mu))
  ) 

df4 %>% ggplot(
    aes(
      color=as.factor(mu),
      x=sample_m
    )
  ) + 
  geom_density(
    size=1
  ) +
  theme_bw() +
  ggtitle("Sampling distributions when mu= 0 or 1, n=20")+
  theme(
    text = element_text(size=15)
  )

  ggsave(
    filename="sampling_dist_2.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)

```
```{r}
df5 <- tibble(
  mu = rep(c(0,1),10000)
) %>%  
  rowwise %>% 
  mutate(
    tidy(t.test(rnorm(20,mu)))
  ) 
  
```

```{r}
df5 %>% ggplot(
    aes(
      color=as.factor(mu),
      x=p.value
    )
  ) + 
  geom_density(
    size=1
  ) +
  theme_bw() +
  ggtitle("t-test p value distribution when mu= 0 or 1, n=20")+
  theme(
    text = element_text(size=15)
  ) +
  geom_vline(
    xintercept = 0.05,
    linetype = "dashed"
  )

  ggsave(
    filename="pvalue_dist_1.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)
```




```{r}
df6 <- tibble(
  n = rep(c(5, 7, 10),2000)
) %>%  
  rowwise %>% 
  mutate(
    tidy(t.test(rnorm(n), mu=1))
  ) 
  
```

```{r}
df6 %>% 
  ggplot(
    aes(
      color=as.factor(n),
      x=p.value
    )
  ) + 
  geom_density(
    size=1
  ) +
  theme_bw() +
  ggtitle("t-test p value distribution for different n when mu = 1")+
  theme(
    text = element_text(size=15)
  ) +
  geom_vline(
    xintercept = 0.05,
    linetype = "dashed"
  ) +
  ylim(-10,20)

  ggsave(
    filename="pvalue_dist_2.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)
```
```{r}
df7 <- tibble(
  n = rep(seq(7,15),2000)
) %>%  
  rowwise %>% 
  mutate(
    tidy(t.test(rnorm(n), mu=1))
  ) 
```

```{r}
df7 %>% 
  group_by(n) %>% 
  summarise(
    power = mean(p.value < .05)
  ) %>% 
  ggplot(
    aes(
      y=power,
      x=n
    )
  ) +
  geom_line() +
  geom_point() +
  theme_bw() +
  ggtitle("power for different sample sizes")+
  theme(
    text = element_text(size=15)
  ) +
  geom_hline(
    yintercept = 0.8,
    linetype = "dashed"
  )

  ggsave(
    filename="power_curve_0.png",
    units="px",
    width=1920,
    height = 1080,
    dpi = 300)
```



